"""
database/db_client.py — Supabase Connection Wrapper for Agent-B

PURPOSE:
    Provides two simple functions that the rest of the project uses to
    interact with Supabase. No other file in the project should create
    a Supabase client directly.

FUNCTIONS:
    get_client(use_secret=True)
        Returns an authenticated Supabase client instance.
        - use_secret=True  → uses the Secret key (for INSERT operations)
        - use_secret=False → uses the Publishable key (for SELECT only)

    insert_prediction(data: dict)
        Takes a dictionary matching the agent_b_predictions columns
        and inserts it as a single row. Returns the inserted row data.

HOW SUPABASE CLIENT WORKS:
    The supabase-py library communicates with your database via REST API
    (HTTP requests). It does NOT open a persistent database connection.
    This means:
    - No connection pools to manage
    - No "connection timeout" issues
    - Each call is an independent HTTP request
    - Safe to use in serverless environments (like Modal)
"""

from supabase import create_client, Client
from config.settings import (
    SUPABASE_URL,
    SUPABASE_PUBLISHABLE_KEY,
    SUPABASE_SECRET_KEY,
)

# ---------------------------------------------------------------------------
# Table name constant — used everywhere to avoid typos
# ---------------------------------------------------------------------------
TABLE_NAME = "agent_b_predictions"


def get_client(use_secret: bool = True) -> Client:
    """
    Create and return a Supabase client.

    Parameters
    ----------
    use_secret : bool, default True
        - True  → uses SUPABASE_SECRET_KEY (full access, bypasses RLS)
                   Used by: Modal pipeline to INSERT predictions
        - False → uses SUPABASE_PUBLISHABLE_KEY (read-only via RLS)
                   Used by: Next.js dashboard, or read-only scripts

    Returns
    -------
    Client
        An authenticated supabase-py Client instance.

    Example
    -------
    >>> client = get_client(use_secret=True)
    >>> client.table("agent_b_predictions").select("*").execute()
    """
    key = SUPABASE_SECRET_KEY if use_secret else SUPABASE_PUBLISHABLE_KEY
    return create_client(SUPABASE_URL, key)


def insert_prediction(data: dict) -> dict:
    """
    Insert a single prediction row into the agent_b_predictions table.

    Parameters
    ----------
    data : dict
        A dictionary containing the prediction data. Keys must match the
        column names in the database table. Example:
        {
            "date": "2026-06-10T00:00:00+05:30",
            "actual_close": 72.45,
            "dxy_value": 104.32,
            "holiday_flag": 0,
            "fingpt_sentiment": 0.65,
            "pred_1d_10th": 70.10,
            "pred_1d_50th": 72.50,
            "pred_1d_90th": 75.20,
            "pred_1m_10th": 68.00,
            "pred_1m_50th": 73.00,
            "pred_1m_90th": 78.50,
            "pred_3m_10th": 65.00,
            "pred_3m_50th": 74.00,
            "pred_3m_90th": 82.00,
            "pred_volatility": 5.10,
            "pred_ma_crossover": 1,
        }

        Note: "id" and "created_at" are auto-generated by the database,
        so you do NOT include them in this dictionary.

    Returns
    -------
    dict
        The inserted row as returned by Supabase (includes the auto-generated
        id and created_at values).

    Raises
    ------
    Exception
        If the INSERT fails (e.g., duplicate date, network error).
    """
    client = get_client(use_secret=True)
    response = client.table(TABLE_NAME).insert(data).execute()
    return response.data
